version: "3"
services:
  api:
    build: .
    restart: always
    ports: 
      - "8000:8000"  #<port on localhost>:<port on containers>
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#   env_file:
#   - ./.env
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=15432
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=dulcinea
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on: 
      - db


  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dulcinea
      - POSTGRES_PASSWORD=root
    volumes:  
      - /opt/data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=dulcinea@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2222!
    ports:
      - "16543:80"
    depends_on: 
      - db

