version: "3"
services:
  api:
    image: monikabril/apis_api
    restart: always
    ports: 
      - "80:8000"  
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#   env_file:
#   - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOTSNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOEKN_EXPIRE_MINUTES}
    depends_on: 
      - db


  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:  
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:


