name: Build and deploy Code
# on: [push, pull_request] Run on all branches when push all pull request
on: 
  push: 
    branches: 
      - 'main'
      - 'test'
      - 'feature_branch'
  pull_request:
    branches:
      - "test_branch"
      - "main"
env:
  DATABASE_HOSTNAME: localhost
  DATABASE_PORT: 5432
  DATABASE_PASSWORD: password123
  DATABASE_NAME: fastapi
  DATABASE_USERNAME: postgres
  SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: start the action
        run: echo "hello this is initialized"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          architecture: 'x64'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest
  