name: Build and deploy Code
# on: [push, pull_request] Run on all branches when push all pull request
on: 
  push: 
    branches: 
      - 'main'
      - 'test'
      - 'feature_branch'
  pull_request:
    branches:
      - "test_branch"
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: start the action
        run: echo "hello this is initialized"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          architecture: 'x64'
      - name: pdate pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
  